"""make_red_flag_physician_id_nullable

Revision ID: 90311ef16fe8
Revises: 001
Create Date: 2026-04-09 17:54:08.739373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90311ef16fe8'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use IF NOT EXISTS throughout so re-running against a DB that already has
    # these objects (e.g. from a prior manual apply) is safe.
    op.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS staff_messages (
            id          UUID        NOT NULL PRIMARY KEY,
            sender_id   UUID        NOT NULL REFERENCES users(id),
            recipient_id UUID       NOT NULL REFERENCES users(id),
            appointment_id UUID              REFERENCES appointments(id),
            content     TEXT        NOT NULL,
            is_read     BOOLEAN     NOT NULL,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """))
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_staff_messages_appointment_id "
        "ON staff_messages (appointment_id)"
    ))
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_staff_messages_recipient_id "
        "ON staff_messages (recipient_id)"
    ))
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_staff_messages_sender_id "
        "ON staff_messages (sender_id)"
    ))

    # ALTER COLUMN is idempotent in Postgres (nullable=True on an already-nullable
    # column is a no-op), so no guard is needed.
    op.alter_column('red_flag_alerts', 'physician_id',
               existing_type=sa.UUID(),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('red_flag_alerts', 'physician_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_staff_messages_sender_id'), table_name='staff_messages')
    op.drop_index(op.f('ix_staff_messages_recipient_id'), table_name='staff_messages')
    op.drop_index(op.f('ix_staff_messages_appointment_id'), table_name='staff_messages')
    op.drop_table('staff_messages')
    # ### end Alembic commands ###
