"""make_red_flag_physician_id_nullable

Revision ID: 90311ef16fe8
Revises: 001
Create Date: 2026-04-09 17:54:08.739373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90311ef16fe8'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_messages',
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_messages_appointment_id'), 'staff_messages', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_staff_messages_recipient_id'), 'staff_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_staff_messages_sender_id'), 'staff_messages', ['sender_id'], unique=False)
    op.alter_column('red_flag_alerts', 'physician_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('red_flag_alerts', 'physician_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_staff_messages_sender_id'), table_name='staff_messages')
    op.drop_index(op.f('ix_staff_messages_recipient_id'), table_name='staff_messages')
    op.drop_index(op.f('ix_staff_messages_appointment_id'), table_name='staff_messages')
    op.drop_table('staff_messages')
    # ### end Alembic commands ###
