"""Conversation / intake-session schemas."""

from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field, field_validator


class ConversationStart(BaseModel):
    """Payload to start a new AI intake conversation."""

    visit_type: str = Field(..., min_length=1, max_length=100)
    disclaimer_accepted: bool

    @field_validator("disclaimer_accepted")
    @classmethod
    def must_accept_disclaimer(cls, v: bool) -> bool:
        if not v:
            raise ValueError("Disclaimer must be accepted to start a conversation")
        return v


class ConversationMessage(BaseModel):
    """A single message in the conversation."""

    role: str = Field(..., pattern=r"^(patient|ai|system)$")
    content: str = Field(..., min_length=1)
    content_type: str = Field(default="text", pattern=r"^(text|voice_transcript)$")


class ConversationResponse(BaseModel):
    """Current state of an intake conversation."""

    session_id: UUID
    status: str
    messages: list[ConversationMessage]
    questions_asked_count: int = Field(..., ge=0)


class FollowUpQuestion(BaseModel):
    """A follow-up question generated by the AI."""

    question_text: str = Field(..., min_length=1)
    question_type: str = Field(..., pattern=r"^(yes_no|short_answer)$")
    domain: str = Field(..., min_length=1, max_length=100)


class PatientAnswer(BaseModel):
    """Patient's answer to a follow-up question."""

    session_id: Optional[UUID] = None
    question_sequence: Optional[int] = Field(default=None, ge=0)
    answer_text: str = Field(..., min_length=1, max_length=5000)


class VoiceNoteUpload(BaseModel):
    """Metadata for a voice-note upload."""

    audio_format: str = Field(..., pattern=r"^(wav|mp3|ogg|webm|m4a)$")
    language_hint: Optional[str] = Field(default=None, max_length=10)


class TranscriptConfirmation(BaseModel):
    """Patient confirms or corrects the AI-generated transcript."""

    session_id: Optional[UUID] = None
    transcript_text: str = Field(..., min_length=1, max_length=10000)
    confirmed: bool


class Concern(BaseModel):
    """A single patient concern with priority."""

    text: str = Field(..., min_length=1, max_length=500)
    priority: int = Field(..., ge=1, le=3)


class ConcernRanking(BaseModel):
    """Top concerns (max 3) ranked by priority."""

    concerns: list[Concern] = Field(..., min_length=1, max_length=3)

    @field_validator("concerns")
    @classmethod
    def unique_priorities(cls, v: list[Concern]) -> list[Concern]:
        priorities = [c.priority for c in v]
        if len(priorities) != len(set(priorities)):
            raise ValueError("Each concern must have a unique priority")
        return v
